import Layout from '../components/layout'

class ReactWr extends React.Component {
    render () {
        return (
            <Layout>
                <div style={{maxWidth: 800, margin: '100px auto 0 auto'}}>
                <h2 style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '14pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#ff6600', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>VINLASTING</span><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> CUNG CẤP CÁC&nbsp;DỊCH VỤ</span></h2>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><strong><span style={{fontSize: '18pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>DESIGN:</span></strong></p>
                <ul style={{marginTop: '0pt', marginBottom: '0pt'}}>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Tư vấn xây dựng thương hiệu</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Thiết kế logo</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Thiết kế hệ thống nhận diện thương hiệu.</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Thiết kế đồ họa: Poster, print ad, catalogue, brochure, packing</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Thiết kế truyền thông đa phương tiện: Web, Flash….</span></li>
                </ul>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><strong><span style={{fontSize: '18pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>PRINTING:</span></strong></p>
                <ul style={{marginTop: '0pt', marginBottom: '0pt'}}>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>In ấn các ấn phẩm phục vụ chiến lược quảng cáo.</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Các ấn phẩm văn phòng (bao Thư, giấy tiêu đề, giấy cacbon nhiều liên, hóa đơn và các loại biểu mẫu khác…)</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Ấn phẩm quảng cáo (Catalogue, poster, brochue, leaflet, folder, túi giấy, túi sách, tờ rơi…)</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Bao bì hộp giấy</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Lịch độc quyền</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Các loại tem, nhãn. (Phiếu giữ xe, vé vào cổng, các phiếu có in số)</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>In bạt khổ lớn nhỏ</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>In decan</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>In tranh dán tường, treo tường</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển quảng cáo ốp Aluminium</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển quảng cáo chữ nổi</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển chữ nổi, Đồng, Inox, Mika ..vvv</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Hộp đèn siêu mỏng</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển tên công ty, phòng ban, chức danh</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển chỉ dẫn, biển số nhà</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển vẫy quảng cáo</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển quảng cáo đèn Led</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Khay mika, kệ mika để bàn, menu mika, cup mika, phale…</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Cung cấp cỏ nhân tạo trang trí nội thất và ngoài trời.</span></li>
                </ul>
                </div>

            </Layout>
        )
    }
}

export default ReactWr