import Layout from '../components/layout'

class ReactWr extends React.Component {
    render () {
        return (
            <Layout>
                <div style={{maxWidth: 800, margin: '100px auto 0 auto'}}>
                <h2 style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '14pt', textAlign: 'center', backgroundColor: '#ffffff'}}><span style={{fontSize: '13.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>CÔNG TY </span><span style={{fontSize: '13.5pt', fontFamily: '"Times New Roman"', color: '#ff6600', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>VINLASTING</span><span style={{fontSize: '13.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> XIN GỬI TỚI QUÝ VỊ </span></h2>
                <h2 style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '14pt', textAlign: 'center', backgroundColor: '#ffffff'}}><span style={{fontSize: '13.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>LỜI CHÀO TRÂN TRỌNG NHẤT.</span></h2>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ngày nay, đời sống kinh tế xã hội ngày càng phát triển thì nhu cầu về quảng cáo, quảng bá hình ảnh của các cá nhân, tổ chức, công ty ngày càng nhiều và đa dạng hơn. Cùng với đó thì khách hàng cũng ngày càng khắt khe hơn với những ấn phẩm quảng cáo – những thông điệp mà bất cứ doanh nghiệp nào cũng cần phải có để tiếp cận thị trường, tiếp cận Khách hàng tiềm năng của mình.</span></p>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Là một Doanh nghiệp chuyên ngành in ấn, thiết kế website, viết phần mềm, chúng tôi mong muốn được góp một phần công sức của mình vào sự thành công của quý vị.</span></p>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Hiện nay, Công ty </span><strong><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#ff6600', backgroundColor: 'transparent', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Vinlasting</span></strong><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> chúng tôi có một đội ngũ nhân viên lành nghề trong lĩnh vực thiết kế &nbsp;và in ấn, cùng trang thiết bị máy móc đầy đủ để đáp ứng các yêu cầu về thiết kế website, viết phần mềm và in ấn chất lượng cao cho các loại sản phẩm, dịch vụ.</span></p>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mục tiêu </span><strong><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#ff6600', backgroundColor: 'transparent', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Vinlasting</span></strong><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> của chúng tôi là đem đến cho quý vị những sản phẩm có chất lượng hoàn hảo nhất cùng với sự phục vụ nhiệt tình, sẵn sàng đáp ứng mọi yêu cầu của quý vị trong thời gian sớm nhất. Chúng tôi cam kết sẽ làm hài lòng quý vị về chất lượng sản phẩm với mức giá cạnh tranh, chắc chắn sẽ đem lại hiệu quả tối đa cho lĩnh vực quảng cáo sản phẩm và dịch vụ của quý vị.</span></p>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Xin gửi lời chúc sức khỏe và lời chào trân trọng nhất tới mọi thành viên trong Gia Đình Quý Khách !</span><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}><br /></span><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Sự thành công của quý vị cũng chính là điều mong muốn nhất của chúng tôi.</span></p>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rất mong nhận được sự quan tâm và hợp tác của Quý vị.</span></p>
                <h2 style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '14pt', backgroundColor: '#ffffff'}}>&nbsp;</h2>
                <h2 style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '14pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>GIÁ TRỊ CỐT LÕI:</span></h2>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '13.999999999999998pt', fontFamily: '"Times New Roman"', color: '#ff6600', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#ff6600', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>GIÁ TRỊ BỀN VỮNG</span></p>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}>&nbsp;</p>
                <h2 style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '14pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>TẦM NHÌN CỦA&nbsp;CHÚNG TÔI:</span></h2>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Luôn phấn đấu để trở thành Công ty hàng đầu về công nghệ.</span></p>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Trở thành một nhà Thiết Kế website, Viết phần mềm, &nbsp;In Ấn chuyên nghiệp, Cho ra những sản phẩm, dịch vụ chất lượng tốt nhất, với mức giá cạnh tranh.</span></p>
                <h2 style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '14pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>SỨ MỆNH CỦA&nbsp;CHÚNG TÔI:</span></h2>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><strong><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#ff6600', backgroundColor: 'transparent', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Vinlasting</span></strong><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> luôn có đội ngũ nhân viên luôn tìm tòi, khám phá, sáng tạo những ý tưởng đột phá. Cùng với máy móc hiện đại cho ra những sản phẩm in chất lượng tốt nhất. Nâng cao hiệu quả kinh doanh của khách hàng.</span></p>
                <h2 style={{lineHeight: '1.295', marginTop: '0pt', marginBottom: '14pt', backgroundColor: '#ffffff'}}><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#ff6600', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>VINLASTING</span><span style={{fontSize: '12pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'small-caps', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}> CUNG CẤP CÁC&nbsp;DỊCH VỤ</span></h2>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><strong><span style={{fontSize: '18pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>DESIGN:</span></strong></p>
                <ul style={{marginTop: '0pt', marginBottom: '0pt'}}>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Tư vấn xây dựng thương hiệu</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Thiết kế logo</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Thiết kế hệ thống nhận diện thương hiệu.</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Thiết kế đồ họa: Poster, print ad, catalogue, brochure, packing</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Thiết kế truyền thông đa phương tiện: Web, Flash….</span></li>
                </ul>
                <p style={{lineHeight: '1.2', marginTop: '0pt', marginBottom: '5pt', backgroundColor: '#ffffff'}}><strong><span style={{fontSize: '18pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>PRINTING:</span></strong></p>
                <ul style={{marginTop: '0pt', marginBottom: '0pt'}}>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>In ấn các ấn phẩm phục vụ chiến lược quảng cáo.</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Các ấn phẩm văn phòng (bao Thư, giấy tiêu đề, giấy cacbon nhiều liên, hóa đơn và các loại biểu mẫu khác…)</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Ấn phẩm quảng cáo (Catalogue, poster, brochue, leaflet, folder, túi giấy, túi sách, tờ rơi…)</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Bao bì hộp giấy</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Lịch độc quyền</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Các loại tem, nhãn. (Phiếu giữ xe, vé vào cổng, các phiếu có in số)</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>In bạt khổ lớn nhỏ</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>In decan</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>In tranh dán tường, treo tường</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển quảng cáo ốp Aluminium</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển quảng cáo chữ nổi</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển chữ nổi, Đồng, Inox, Mika ..vvv</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Hộp đèn siêu mỏng</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển tên công ty, phòng ban, chức danh</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển chỉ dẫn, biển số nhà</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển vẫy quảng cáo</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Biển quảng cáo đèn Led</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Khay mika, kệ mika để bàn, menu mika, cup mika, phale…</span></li>
                    <li style={{listStyleType: 'disc', fontSize: '10pt', fontFamily: '"Noto Sans Symbols"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre'}}><span style={{fontSize: '10.5pt', fontFamily: '"Times New Roman"', color: '#006666', backgroundColor: 'transparent', fontWeight: 400, fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap'}}>Cung cấp cỏ nhân tạo trang trí nội thất và ngoài trời.</span></li>
                </ul>
                </div>

            </Layout>
        )
    }
}

export default ReactWr